### ISSUE TITLE
How to solve "Fooocus exists but remote URL will be updated.Fooocus exists, but not a git repo. "

### ISSUE THREAD

**Issue by daquangao** [mrhan1993/Fooocus-API#189]
<img width="851" alt="2024-01-23 193636" src="https://github.com/konieshadow/Fooocus-API/assets/100754650/9246ae20-ad04-42ba-87b3-f07a313017e3">

Unable to start.
How to solve the problem?
thanks!

**Comment by konieshadow** [comment]
@daquangao Did you copy to the repositories/Fooocus folder from other place? Or could you check if where is a '.git' folder under repositories/Fooocus?

**Comment by mrhan1993** [comment]
do not use Download ZIP, use git clone, or level repositories dir empty, app will process all things. if you have models, you can move it out, and then run app, when it finished, copy models back

**Comment by miklosme** [comment]
I had this problem because I was eager and git cloned the repo before starting the Docker. The right order is first to make the `repositories` folder and **leave it empty**, start Docker, let it clone, and after that you can copy the models.

My guess is it's a compatibility mismatch between the host systems's git version and the one used by the container. I was trying to use `git version 2.43.0.windows.1`.
