### ISSUE TITLE
Can we use the Juggernaut model used in this repo for free in our own api project? The Rundiffusion huggingface page says that models are not allowed to be used as api.

### ISSUE THREAD

**Issue by MMucahit** [mrhan1993/Fooocus-API#256]

**Comment by mrhan1993** [comment]
I will check it later

**Comment by davefojtik** [comment]
The licence for the model is on its [CivitAI](https://civitai.com/models/133005?modelVersionId=288982) page. See the [CreativeML Open RAIL++-M](https://github.com/Stability-AI/generative-models/blob/main/model_licenses/LICENSE-SDXL1.0) and study it for your use case. All I could see by quickly going through it is that you can use the model as an API service and commercially if you adhere to a couple of rules. Like presenting your users with that same licence and copyright notices of the model, and introducing your own system to comply with the rules specified in the last paragraph "A Use Restrictions" (basically ensuring your users don't do illegal things with it)

**Comment by mrhan1993** [comment]
License:
creativeml-openrail-m

The full content is located at：https://huggingface.co/spaces/CompVis/stable-diffusion-license/raw/main/license.txt

The sections on distribution are as follows:

4. Distribution and Redistribution. You may host for Third Party remote access purposes (e.g. software-as-a-service), reproduce and distribute copies of the Model or Derivatives of the Model thereof in any medium, with or without modifications, provided that You meet the following conditions:
Use-based restrictions as referenced in paragraph 5 MUST be included as an enforceable provision by You in any type of legal agreement (e.g. a license) governing the use and/or distribution of the Model or Derivatives of the Model, and You shall give notice to subsequent users You Distribute to, that the Model or Derivatives of the Model are subject to paragraph 5. This provision does not apply to the use of Complementary Material.
You must give any Third Party recipients of the Model or Derivatives of the Model a copy of this License;
You must cause any modified files to carry prominent notices stating that You changed the files;
You must retain all copyright, patent, trademark, and attribution notices excluding those notices that do not pertain to any part of the Model, Derivatives of the Model.
You may add Your own copyright statement to Your modifications and may provide additional or different license terms and conditions - respecting paragraph 4.a. - for use, reproduction, or Distribution of Your modifications, or for any such Derivatives of the Model as a whole, provided Your use, reproduction, and Distribution of the Model otherwise complies with the conditions stated in this License.

As I understand it, it is OK to use it in the API, but it needs to be explained in the License. I'm not in a position to do this right now, so if you want to continue using it, read the original license and use it as stated in it. After I finish my personal business, I will update the license.

**Comment by rundiffusion** [comment]
@MMucahit Reach out to juggernaut@rundiffusion.com we want to support you using Juggernaut, even commercially.
