### ISSUE TITLE
Generating NSFW compliant images

### ISSUE THREAD

**Issue by DisantHoridnt** [mrhan1993/Fooocus-API#338]
**Description:**

Thank you for great job that you are doing with FooocusApi.

We are attempting to incorporate NSFW models into our API built from the repo-- [Fooocus-API](https://github.com/mrhan1993/Fooocus-API). We have added some new models to have the API generate NSFW compliant images. However, we are currently facing an issue where the app does not generate any images. Do you have any ideas on how to integrate nsfw into the repo?

**Expected Behavior:**
The app should generate NSFW compliant images.

**Actual Behavior:**
The models take an excessively long time to load and do not generate any images.

**Attachments:**
![Screen recording](https://drive.google.com/file/d/13rpa9yLfCBCZAvyJ367UvmgQap74EDTb/view?usp=drive_link)

**Additional Context:**
We are using the following environment setup:
- OS: Ubuntu 22.04 Ampere A100 (40 GB GPU memory)
- Python Version: 3.10

**Comment by davefojtik** [comment]
This sounds more like a problem with the specific model you're trying to use. Neither Fooocus nor Fooocus-API are censored and are generating NSFW images just fine. The screen recording you attached cannot be played, therefore more info about the model or what's happening is needed.

**Comment by pribeh** [comment]
Hi @davefojtik , thank you for your response. Let me see if I can clarify a few things. The issue is that it looks like new changes are coming to Fooocus library that appear to break Fooocus API requests from our initial tests. Let me provide some context

We're testing out a new feature that utilizes models that help to filter OUT NSFW content – that black them out – introduced in this pull request 

https://github.com/lllyasviel/Fooocus/pull/958

The feature is available in the "develop"  branch ([here](https://github.com/lllyasviel/Fooocus/commit/00d3d1b4b31b2effa32f6eb96f8e5caf6368f8e3)) and will be introduced into master soon I presume. We've tested this branch as well as @mashb1t's fork of Fooocus ([here](https://github.com/mashb1t/Fooocus)) and each time it breaks our text-to-image requests.

We brought it up with the maintainers of the Fooocus library ([here](https://github.com/lllyasviel/Fooocus/pull/958#issuecomment-2127392283)) and they suggested we raise the issue here.

We did also set the NSFW config boolean to false and the request also produces an error. The only type of successful response we got was when making a ping pong request.

We can confirm that the Fooocus library is running 

**Steps to reproduce:** 

- Replace the 9 files/folders in repositories/fooocus with the contents of the develop Fooocus branch
- Search for NSFW boolean in config.py file 
- Set it to true or false
- Run Fooocus with the Fooocus API
- Run a text-to-image request

**Result:**

```
foocus-api          | [2024-05-24 04:47:29] INFO     [Task Queue] Waiting for task finished, job_id=a8767989-161e-4eb1-8a78-e2b8e699b14d
fooocus-api          | Exception in thread Thread-2 (task_schedule_loop):
fooocus-api          | Traceback (most recent call last):
fooocus-api          |   File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
fooocus-api          |     self.run()
fooocus-api          |   File "/usr/lib/python3.10/threading.py", line 953, in run
fooocus-api          |     self._target(*self._args, **self._kwargs)
fooocus-api          |   File "/opt/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
fooocus-api          |     return func(*args, **kwargs)
fooocus-api          |   File "/opt/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
fooocus-api          |     return func(*args, **kwargs)
fooocus-api          |   File "/app/fooocusapi/worker.py", line 47, in task_schedule_loop
fooocus-api          |     process_generate(current_task)
fooocus-api          |   File "/opt/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
fooocus-api          |     return func(*args, **kwargs)
fooocus-api          |   File "/opt/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
fooocus-api          |     return func(*args, **kwargs)
fooocus-api          |   File "/app/fooocusapi/worker.py", line 94, in process_generate
fooocus-api          |     from modules.sdxl_styles import apply_style, fooocus_expansion, apply_wildcards
fooocus-api          | ImportError: cannot import name 'apply_wildcards' from 'modules.sdxl_styles' (/app/repositories/Fooocus/modules/sdxl_styles.py)
```

**Comment by mashb1t** [comment]
@pribeh the error message hints at apply_wildcards not being in modules.sdxl_styles, but both Fooocus and Fooocus-API have the method there. Is it possible that this method has been deleted by accident in your code?

**Comment by davefojtik** [comment]
> Replace the 9 files/folders in repositories/fooocus with the contents of the develop Fooocus branch

You can't just replace the supported Fooocus with a different fork, newer version or in this case even a dev branch and expect it to work flawlessly. The API is written for a specific version for a reason. I suggest waiting for it to be released both in Fooocus and then in Fooocus-API or helping to add it via [pull request](https://github.com/mrhan1993/Fooocus-API/pulls) so it can be added in the next compatibility update.

**Comment by mrhan1993** [comment]
@PrinceDisant @pribeh 
I pushed dev branch that support to Fooocus Dev branch

After the preliminary test, nsfw checker is work well. If you want to block nsfw result, set `black_out_nsfw` to true in advanced_params, it will return a black image if result is nsfw.

you can do more test, if any questions, reply here

**Comment by PrinceDisant** [comment]
Does it work in fooocus API?

**Comment by DisantHoridnt** [comment]
It actually worked! I was able to integrate, I was missing the advanced params integration. Thank you so much @mrhan1993 and @mashb1t for this. Our users would not be able to use our app safely.
Please check out our platform here: https://rebl.ai/
